import { Lead, Agent, ClinicBranch, CallLog } from './types';

export const mockLeads: Lead[] = [
  {
    id: '1',
    name: 'Ahmed Hassan',
    nameAr: 'أحمد حسن',
    email: 'ahmed.hassan@example.com',
    phone: '+966501234567',
    clinic: 'Riyadh Central',
    priority: 'high',
    slaStatus: 'critical',
    source: 'website',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    lastContactAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    nextFollowUp: new Date(Date.now() + 24 * 60 * 60 * 1000),
    notes: 'Interested in cataract surgery consultation',
    assignedAgent: 'Fatima Al-Rashid',
    callHistory: [
      {
        id: 'call1',
        leadId: '1',
        date: new Date(Date.now() - 2 * 60 * 60 * 1000),
        duration: 12,
        notes: 'Patient inquired about surgery timeline',
        outcome: 'scheduled',
        agentName: 'Fatima Al-Rashid',
      },
      {
        id: 'call2',
        leadId: '1',
        date: new Date(Date.now() - 24 * 60 * 60 * 1000),
        duration: 8,
        notes: 'Initial consultation call',
        outcome: 'interested',
        agentName: 'Mohammed Saleh',
      },
    ],
  },
  {
    id: '2',
    name: 'Mona Zaki',
    nameAr: 'منى زكي',
    email: 'mona.zaki@example.com',
    phone: '+966502234567',
    clinic: 'Jeddah Branch',
    priority: 'medium',
    slaStatus: 'warning',
    source: 'referral',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    lastContactAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
    nextFollowUp: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    notes: 'Referred by Dr. Ibrahim for laser treatment',
    assignedAgent: 'Karim Abdullah',
    callHistory: [
      {
        id: 'call3',
        leadId: '2',
        date: new Date(Date.now() - 8 * 60 * 60 * 1000),
        duration: 15,
        notes: 'Discussed treatment options',
        outcome: 'interested',
        agentName: 'Karim Abdullah',
      },
    ],
  },
  {
    id: '3',
    name: 'Samira Al-Otaibi',
    nameAr: 'سميرة العتيبي',
    email: 'samira.otaibi@example.com',
    phone: '+966503234567',
    clinic: 'Dammam Branch',
    priority: 'high',
    slaStatus: 'ok',
    source: 'phone',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    lastContactAt: new Date(Date.now() - 30 * 60 * 1000),
    nextFollowUp: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    notes: 'Urgent eye examination needed',
    assignedAgent: 'Noor Mansour',
    callHistory: [
      {
        id: 'call4',
        leadId: '3',
        date: new Date(Date.now() - 30 * 60 * 1000),
        duration: 6,
        notes: 'Scheduled appointment',
        outcome: 'scheduled',
        agentName: 'Noor Mansour',
      },
    ],
  },
  {
    id: '4',
    name: 'Rajesh Patel',
    nameAr: 'راجيش باتيل',
    email: 'rajesh.patel@example.com',
    phone: '+966504234567',
    clinic: 'Riyadh Central',
    priority: 'low',
    slaStatus: 'overdue',
    source: 'social',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    lastContactAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    nextFollowUp: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    notes: 'Follow-up on previous inquiry',
    callHistory: [
      {
        id: 'call5',
        leadId: '4',
        date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
        duration: 5,
        notes: 'Patient not interested',
        outcome: 'not-interested',
        agentName: 'Fatima Al-Rashid',
      },
    ],
  },
  {
    id: '5',
    name: 'Leila Mansouri',
    nameAr: 'ليلى منصوري',
    email: 'leila.mansouri@example.com',
    phone: '+966505234567',
    clinic: 'Jeddah Branch',
    priority: 'medium',
    slaStatus: 'ok',
    source: 'website',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    lastContactAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    nextFollowUp: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    notes: 'Interested in corneal treatment',
    assignedAgent: 'Karim Abdullah',
    callHistory: [],
  },
  {
    id: '6',
    name: 'Hassan Al-Dosari',
    nameAr: 'حسن الدوسري',
    email: 'hassan.dosari@example.com',
    phone: '+966506234567',
    clinic: 'Dammam Branch',
    priority: 'high',
    slaStatus: 'warning',
    source: 'referral',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    lastContactAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    nextFollowUp: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    notes: 'VIP patient - requires priority handling',
    assignedAgent: 'Noor Mansour',
    callHistory: [
      {
        id: 'call6',
        leadId: '6',
        date: new Date(Date.now() - 4 * 60 * 60 * 1000),
        duration: 20,
        notes: 'Extended consultation',
        outcome: 'scheduled',
        agentName: 'Noor Mansour',
      },
    ],
  },
];

export const mockAgents: Agent[] = [
  {
    id: 'agent1',
    name: 'Fatima Al-Rashid',
    email: 'fatima.rashid@eyeworld.com',
    role: 'agent',
    clinic: 'Riyadh Central',
    activeCalls: 2,
    totalBookings: 24,
    avgCallDuration: 11,
  },
  {
    id: 'agent2',
    name: 'Mohammed Saleh',
    email: 'mohammed.saleh@eyeworld.com',
    role: 'agent',
    clinic: 'Riyadh Central',
    activeCalls: 1,
    totalBookings: 19,
    avgCallDuration: 9,
  },
  {
    id: 'agent3',
    name: 'Karim Abdullah',
    email: 'karim.abdullah@eyeworld.com',
    role: 'agent',
    clinic: 'Jeddah Branch',
    activeCalls: 3,
    totalBookings: 31,
    avgCallDuration: 13,
  },
  {
    id: 'agent4',
    name: 'Noor Mansour',
    email: 'noor.mansour@eyeworld.com',
    role: 'agent',
    clinic: 'Dammam Branch',
    activeCalls: 0,
    totalBookings: 28,
    avgCallDuration: 12,
  },
];

export const mockClinics: ClinicBranch[] = [
  {
    id: 'clinic1',
    name: 'Riyadh Central',
    city: 'Riyadh',
    manager: 'Dr. Ibrahim Al-Saud',
    leadsCount: 42,
    bookingsCount: 18,
  },
  {
    id: 'clinic2',
    name: 'Jeddah Branch',
    city: 'Jeddah',
    manager: 'Dr. Fatima Al-Noor',
    leadsCount: 38,
    bookingsCount: 14,
  },
  {
    id: 'clinic3',
    name: 'Dammam Branch',
    city: 'Dammam',
    manager: 'Dr. Khalid Al-Khudairi',
    leadsCount: 35,
    bookingsCount: 12,
  },
];
